name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    # runs-on: ubuntu-latest
    runs-on: [self-hosted]
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # # Git LFS
      # - name: Create LFS file list
      #   run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      # - name: Restore LFS cache
      #   uses: actions/cache@v2
      #   id: lfs-cache
      #   with:
      #     path: .git/lfs
      #     key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      # - name: Git LFS Pull
      #   run: |
      #     git lfs pull
      #     git add .
      #     git reset --hard

      # # Cache
      # - uses: actions/cache@v2
      #   with:
      #     path: Library
      #     key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #     restore-keys: |
      #       Library-

      # # Test
      # - name: Run tests
      #   uses: game-ci/unity-builder@v2
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: |
            <?xml version="1.0" encoding="UTF-8"?><root>
                <License id="Terms">
                    <MachineBindings>
                        <Binding Key="1" Value="576562626572264761624c65526f7578"/>
                        <Binding Key="2" Value="576562626572264761624c65526f7578"/>
                    </MachineBindings>
                    <MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM="/>
                    <SerialHash Value="38730ee3dc74a24232646c78e0e4a693abbc69ed"/>
                    <Features>
                        <Feature Value="33"/>
                        <Feature Value="1"/>
                        <Feature Value="12"/>
                        <Feature Value="2"/>
                        <Feature Value="24"/>
                        <Feature Value="3"/>
                        <Feature Value="36"/>
                        <Feature Value="17"/>
                        <Feature Value="19"/>
                        <Feature Value="62"/>
                        <Feature Value="60"/>
                    </Features>
                    <DeveloperData Value="AQAAAEY0LTUyRkUtNFZCVi1SREhNLTIyVDMtUFBaNg=="/>
                    <SerialMasked Value="F4-52FE-4VBV-RDHM-22T3-XXXX"/>
                    <StartDate Value="2022-07-21T00:00:00"/>
                    <StopDate Value="2022-07-25T08:00:58"/>
                    <UpdateDate Value="2022-07-22T07:00:57"/>
                    <InitialActivationDate Value="2022-07-21T05:53:33"/>
                    <LicenseVersion Value="6.x"/>
                    <ClientProvidedVersion Value="2020.3.14f1"/>
                    <AlwaysOnline Value="false"/>
                    <Entitlements>
                        <Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/>
                        <Entitlement Ns="unity_editor" Tag="DarkSkin" Type="EDITOR_FEATURE" ValidTo="9999-12-31T00:00:00"/>
                    </Entitlements>
                </License>
            <Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>24YATCCd+EnuzisST+JYMXzxOkE=</DigestValue></Reference></SignedInfo><SignatureValue>apLqdSAjb/dH53/nlL0naSzSJ6hURh2gtEL1TwdEjVNPdSNGXrWOEb9K6yabdImU0nCVxorM3Zje&#13;
            /DS+r71buPVAEOhaT4IkgaH7irXoEEHYgkivO3QNthRqepiWwKdZecmNOrYzzs32MTGfuPz91vaq&#13;
            c/fLHDjB5UA+ZzZ3s2aDi6Rghy8joKLDHGNqR0v9RZAah+JIT7QoQ+vA5HaQc8NTaeH3n/KRVCLQ&#13;
            NeiHXT6mtxEy8lH9WPYsehFqgbevLH2u1xXdi29CtU7qrdPfracvJ6riE1hSlgka/PQiZd3jRjG6&#13;
            DRoFcA2AWu99Iz+4RUmCGrMbliDQJohF3mPshg==</SignatureValue></Signature></root>
          UNITY_EMAIL: 'taichi-build@proton.moe'
          UNITY_PASSWORD: 'Jtzwscd.1'
          ANDROID_KEYSTORE_NAME: debug.keystore
          ANDROID_KEYSTORE_PASS: android
          ANDROID_KEYALIAS_NAME: androiddebugkey
          ANDROID_KEYALIAS_PASS: android
          ANDROID_KEYSTORE_BASE64: |
            AAAAAgAAABSw73RxVPCsqp6w2Iwn6vRaBVDjigAABggEAA9hbmRyb2lkZGVidWdrZXkAAAGCIBb9
            YgAAAAEABVguNTA5AAAC6DCCAuQwggHMAgEBMA0GCSqGSIb3DQEBBQUAMDcxFjAUBgNVBAMMDUFu
            ZHJvaWQgRGVidWcxEDAOBgNVBAoMB0FuZHJvaWQxCzAJBgNVBAYTAlVTMCAXDTIyMDcxMzEwNDMz
            OVoYDzIwNTIwNzA1MTA0MzM5WjA3MRYwFAYDVQQDDA1BbmRyb2lkIERlYnVnMRAwDgYDVQQKDAdB
            bmRyb2lkMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANS5SY6o
            OGwI5KqPPbVOqQZ1XmWd3wruGPgalOHjEYtcxD/7oUMTBHRaduS7NDRqBW5R3x2LVjQKjW5bmTsL
            XOivhFvw9MvRVaqMD0VPFaqnrYOLQYAvhqyPd+RCtFq1AM7HqrKn5JhQibwOHIgkl1xpQAW//XpY
            isG4HnCyyakhTnhJnWh/PHyZG397HvqrLUelPInOGTc20eZ5NfqUPT7aFBw3V6JwQHY5bbI2mV5E
            VFXk3oNgiOn751S0xLcYLzz2JSSoWeDUE2CMzisNUMpIubiD6UkY0+R1HneXnQtPSy9Vyb8Mpye0
            Z6Z1lhMZc4h9bwS5m35nNKcQGbw51MkCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAD9USe8af0w0y
            chECmQgfGqPn46n7txMLeEnEhF0sp2xi+YLYpPihtrliy7byiudC8VTlG0kbpEjZll5E4Ec2wTPS
            Ex+vzrwsJVHvI5fOXgyvBX+NS6I4qYGQOQ65l7Nw91de1MmgJTrM0hJO12MJzsQyxtu3XyFhgrgT
            5IKms1nSBSAGaKnAS/I/7+6i9vDJeUOGMc+Pt46ECdG+dnPtBzoLVzdRkCWVhoAzEouEoOilDOII
            CPTNYmOVpHHABXuheMPOwIMICAi6m7vi5Ln73LEIFwx+ozNpJbh3MN4dUEOK6wGg66yv2RVpjKAS
            XJCr0XKFiKAWgy5WmpNI35xLSgAABPQAAAAUjOQgoq6W2Fgp86tTuP2/a+rwGIIAAAe6NusVeKjI
            DYyxoYKYHDiyXS7kq46OZRBa+Vhzqx1guy1sQWPK0LnGq6CgeAq2dDTJ/eHlnuEC9DERrUMrEskB
            B8+5Yygw6GtKOGgIhflcxa/8nWl1LjqGivfEFUjmPdvsJSU8rLSmyOL+qYa2x1MX1oh+2inBXA+8
            0c4hgdpEhMdA9OBhZ3rpY/IsroS+FRwAwr70SX3dc1GIAGf6vK67X61vxnyK6lyAlLKoqdzyKnJM
            rsVVWt2RzVDZQTJSWPJ54J7hgYClaSn44Dhz4akILBnOy43tLor/Q1CuL4xnJHgVEUb7MUzV4dxp
            3oSnmMAyUK1wcTu6UQquuiUfuK7RHa1U5ZervplfwtOQ75t+3C8eTcFshyuYCs96Y1xMDGRLKOpY
            PPGAgHgT53cCV0bWwGCMrjlci2MOx4DArsqdI6MZpmnvI/jm/C++nAOwvkkblouphCX+y53ufypk
            MeRLn9LNKfPRHjZdGfP7Up3JvNaOKV7Ty5yyt8BqEBI2FkBkdxvu2Ejo2ya+8Kdjp83l0SOoDZTn
            80kdVRqLZlviOuZSS6dK0k3gVSNmeBGDWJ8teAW6tiD6uOiAvjgYhg3I/56T+iathTyYXWCA9yT1
            LPOEgYjNk8kr/skDqtXz9jv77TLU4rhhi6g8bwCuptlsMF9Q+kzgOeziKFFn/1PsesyoWmHyVt21
            0+89ZCc0cuT1l+LBVC7puiVkl/dcdF7IeTHqiRDv8JVuta10QewRc+pxNV3DzJ8ffq3jzf/mKcoB
            5qdRRzlBGeo2vJi9JNqJXgS96LLGGx7SU5gDNjwxj9vHYm6DD3W+jRDhmvBcOBKAOzhCQ7IW1tpa
            kGaYRfVSNwKIuns5veBZkVasnH2RlclFQAMrZa2frMmYKR2BBenePzRqkn2iHu+LqwgEtGUFhLlx
            pdQ6/l3cUGJaJdyo7/Mtz80GXKWhDQDXZS1pXzTplTCt9mSQ84nVNEUuCloeo3744SI+PmWuBu43
            m7ZLgFKRWaZV/wM9bh6EGpZfJMotrXPPSanEL46UQaJEA97qgBcwuuGzRPLy2bbMcsu6K+BOEqaW
            HTaU1GpHZR89Ihw3QKNHfL6+a69ZPhEDiwtDCNLfp4gTKKWvpxI8GfN9kG955sIl2fNtiuudPgpt
            eBQNoquzmQNqfCa0Wv0piHn+Ti9xR9h2kBGpBTFCjfLUBXJrfDmhSj+GTdVS4P85oNlw1YxV81Io
            f96l8xRv4dENMn5+AYvU7JyF9F4K+vcrY/A4tXF5VuHCrv0t6AvZWkKLz9D7LZwATPtgZMEPfchv
            bsjsJ84xWtz8R+RNp32NX0AxYx9q4Dd34D2CHtiI888X6ejiq1lYz08nv5Hk+HzeUjG2TnesaYUK
            cXErrmZjAZHfX/+bEPMpYRLRIQgqFd4odIsxNXj0jjboMBdiBe6MyK/4BAI28CxVIEGiJOjejvo6
            sHfUQx6257pWON8E6lbNdfhT6Yb2ryH+/ufjNnW7ak24druXOZ0B7GFmxh2ei0Iy6MoqSjusnEf8
            HM4dSAVx6AFaxRGDeoKhwM5tA5EDpq5ma+V7gjCuMTzdAFcGii8DtTay5kknQyqmuqI7V+IKOure
            F+j319D/UudI5JNTPtUT46g7TQU3FH4aGrOVe6jtZp7f0IbEYwCvvdgP59LPi3DFzoWQg9+iDr38
            8w==
        with:
          targetPlatform: Android

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

